### PR TITLE
 support request header & fix deploy bug

### PR DESCRIPTION
**Pull request by boxcc**
### support request header
I use the google map tile, he must use the user agent in the headers, otherwise it will return a 403 error.

```
https://mt1.google.cn/vt/lyrs=m@207000000&hl=zh-CN&gl=CN&src=app&x={x}&y={y}&z={z}&s=Galile
```

### fix deploy bug
I deployed the source code to the server, but I get an error when I enable it.
```
error: Cannot find module 'babel-runtime/regenerator'
```
I found the babel documentation https://babeljs.io/docs/en/babel-plugin-transform-runtime#installation to fix this error.

### CODE REVIEW

**Comment by StephanGeorg** [comment]
Hi @boxcc. Thanks for the PR.

> I use the google map tile, he must use the user agent in the headers, 
> otherwise it will return a 403 error.

Would you pease tell me the excact header, that I can test it?

**Comment by boxcc** [comment]
@StephanGeorg 
```
headers: {
    'User-Agent': 'xxxx',
}
```

**Comment by StephanGeorg** [comment]
But beware:

```
Accessing tiles directly is against the Google Maps Terms of Service.
```

**Comment by StephanGeorg** [comment]
Merged and published to npm. Thanks.

**Comment by boxcc** [comment]
OK, thank you very much  @StephanGeorg

**Pull request merged**
