### PR TITLE
Image.draw(), make compose draw all tiles at once, optimization. Fixe…

### PR DESCRIPTION
**Pull request by JOGUI22**
This fixes Issue #44

For bigger images (that requiles sharp to compose with a lot of tiles) the service was slow. This was due to a sequential composition outside of Sharp. Now Sharp handles the composition of all tiles at once.

For 1080x1080 images, we get from 5 seconds to 1.5 seconds speed improvement in a single request.

### CODE REVIEW

**Comment by StephanGeorg** [comment]
@JOGUI22 Thanks for the PR. Would you please provide a test as well.

**Comment by JOGUI22** [comment]
Hello Stephan,

May I ask for some guidance about what kind of test do you expect that I provide? 
As it's an improvement and not a bugfix about speeding up the algorithm, I don't know how to create a test that validates such improvement.
This is an improvement of a core feature of staticmaps, _merging the tile images into the baselayer_. It's already used in the following tests (any that uses a tileUrl option when creating a map):

- Fetch tiles from subdomains
- Rendering text ... -> Render text on NASA Blue Marble

If these two tests passes, it should also show that this PR passes the tests.

**Comment by StephanGeorg** [comment]
> If these two tests passes, it should also show that this PR passes the tests.

Agree. Thank you for your work and the PR.

**Comment by StephanGeorg** [comment]
Published to npm staticmaps@1.4.3

**Comment by JOGUI22** [comment]
@StephanGeorg Thank you Stephan, happy to work with you. Fast and clean.

See ya next time!

**Pull request merged**
