### PR TITLE
added validation to prevent negative value in composite()

### PR DESCRIPTION
**Pull request by pratikt4f**
---
Note: getting issue when path=41.892986,12.4820967000001|43.7731,11.2559|43.7223534,10.3966957|43.72327,10.39584|43.723333,10.393889|43.731417,7.420275|43.6667,6.9167|43.550861,7.01725|45.465556,9.19|45.470244,9.179549|45.464167,9.191389|45.4412034,12.3154028|45.4335817,12.3378987999999|45.4335817,12.3378987999999|41.892986,12.4820967000001

width=378 and height=264

### CODE REVIEW

**Comment by StephanGeorg** [comment]
Hi @pratikt4f 

Sry for the late response but I had trouble with Github 2FA due to a stolen phone. 

I try to reproduce the error:

```
  const options = {
        width: 378,
        height: 264,
      };

const map = new StaticMaps(options);

const polygon = {
        coords: [
          [41.892986,12.4820967000001],
          [43.7731,11.2559],
          [43.7223534,10.3966957],
          [43.72327,10.39584],
          [43.723333,10.393889],
          [43.731417,7.420275],
          [43.6667,6.9167],
          [43.550861,7.01725],
          [45.465556,9.19],
          [45.470244,9.179549],
          [45.464167,9.191389],
          [45.4412034,12.3154028],
          [45.4335817,12.3378987999999],
          [45.4335817,12.3378987999999],
          [41.892986,12.4820967000001]
    ]};
map.addPolygon(polygon);
```

## Result
07-polygon

**Comment by pratikt4f** [comment]
Hi @StephanGeorg, Thanks for the replay.
for reproducing the issue you need to use a marker. as I checked the issue is due to the marker's top-left position was outbound of an image...

Let me know if need any details
Thanks

**Comment by StephanGeorg** [comment]
Do you have any example data or test case?

> marker's top-left position was outbound of an image...

shouldn't be possible because the bound of all features (markers, lines, ...) is calculated based on their positions. I totally agree with your fix but I want to understand how this can be possible.

Thanks
Stephan

**Comment by pratikt4f** [comment]
Hellow @StephanGeorg, Thanks for understanding.

`Do you have any example data or test case?`
-> Try with marker image and try to draw image like 

image

 Please let me know if any thing 

Thanks
Pratik

**Comment by StephanGeorg** [comment]
Ok, I think you're right:

> shouldn't be possible because the bound of all features (markers, lines, ...) is calculated based on their positions

... but does not include the marker image itself. 


I need to check that case. Thank you.

**Comment by StephanGeorg** [comment]
Bug occurs when using render() with zoom option. I fixed it https://github.com/StephanGeorg/staticmaps/blob/master/src/staticmaps.js#L350 by rejecting markers which would be outside the base image.

**Pull request closed without merging**
