### PR TITLE
Added Math.round to avoid validation errors in Sharp.

### PR DESCRIPTION
**Pull request by gihanshp**
This PR fixes validation errors for Sharp image lib. Following is sample error

```
(node:35913) UnhandledPromiseRejectionWarning: Error: Invalid overlay left 122.5 and/or top 43
    at Sharp.overlayWith (<path>/node_modules/sharp/lib/composite.js:74:15)
    at StaticMaps._callee4$ (<path>/dist/staticmaps.js:407:79)
    at tryCatch (<path>/node_modules/regenerator-runtime/runtime.js:62:40)
    ...
```

Sharp.overlayWith expects integer values for `top` and `left`. Adding Math.round fixed the issue.

### CODE REVIEW

**Comment by StephanGeorg** [comment]
Hm? Maybe it is a sharp bug? Because option.top && option.left expected type is Number: http://sharp.dimens.io/en/stable/api-composite/#overlaywith

**Comment by StephanGeorg** [comment]
Ah, no it is indeed integer: https://github.com/lovell/sharp/blob/7d48a5ccf499c320ff975d2151730d805fcd88ef/lib/composite.js#L70

Thank you for the PR @gihanshp

**Comment by gihanshp** [comment]
Yep, it accepts only integers in code. Might be docs are not in sync with code. 👍

**Comment by StephanGeorg** [comment]
Thanks!

**Pull request merged**
